export const sports = {
  1: "futbol",
  2: "basketbol",
  3: "tennis",
  4: "hokkey",
  5: "boks",
  6: "yengil atletika",
  7: "suv sporti",
  8: "kurash",
  9: "gimnastika",
  10: "voleybol",
  11: "badminton",
  12: "futzal",
  13: "sambo",
  14: "kikboks",
  15: "krav maga",
  16: "dzyudo",
  17: "raqs",
  18: "velosiped sporti",
  19: "skateboarding",
  20: "mini-futbol",
};
